package sapiens

const (
	Gemini AgentType = "gemini"
)

const (
	SEMANTIC_SIMILARITY  EmbeddingType = "SEMANTIC_SIMILARITY"
	CLASSIFICATION       EmbeddingType = "CLASSIFICATION"
	CLUSTERING           EmbeddingType = "CLUSTERING"
	RETRIEVAL_DOCUMENT   EmbeddingType = "RETRIEVAL_DOCUMENT"
	RETRIEVAL_QUERY      EmbeddingType = "RETRIEVAL_QUERY"
	QUESTION_ANSWERING   EmbeddingType = "QUESTION_ANSWERING"
	FACT_VERIFICATION    EmbeddingType = "FACT_VERIFICATION"
	CODE_RETRIEVAL_QUERY EmbeddingType = "CODE_RETRIEVAL_QUERY"
)
